# docker-compose.yml
version: '3'

services:
  php:
    build:
      context: .
    image: narciso/authorizer
    container_name: authorizer
    volumes:
      - .:/var/www/html
    command: [ "./docker-entrypoint.sh" ]